# Generated by Django 5.0.6 on 2024-07-30 18:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("id_user", models.AutoField(primary_key=True, serialize=False)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("password", models.CharField(max_length=128, null=True)),
                ("first_name", models.CharField(max_length=255, null=True)),
                ("last_name", models.CharField(max_length=255, null=True)),
                (
                    "gender",
                    models.SmallIntegerField(
                        choices=[(1, "male"), (2, "female"), (3, "other")]
                    ),
                ),
                (
                    "user_type",
                    models.SmallIntegerField(choices=[(1, "patient"), (2, "doctor")]),
                ),
                ("is_staff", models.BooleanField(default=False)),
                ("is_superuser", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="EmergencyContact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("phone_number", models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name="Doctor",
            fields=[
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        primary_key=True,
                        serialize=False,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("specialty", models.CharField(max_length=255)),
                ("crm", models.CharField(max_length=50, unique=True)),
                ("biography", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="AdditionalInformation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("telephone", models.CharField(max_length=15, null=True)),
                ("date_of_birth", models.DateField(null=True)),
                ("completed_form", models.BooleanField(default=False)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="additional_info",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="LifeHabits",
            fields=[
                ("id_life_habits", models.AutoField(primary_key=True, serialize=False)),
                ("alcohol_consumption", models.BooleanField(default=False)),
                ("use_tabacco", models.BooleanField(default=False)),
                ("physical_activity", models.BooleanField(default=False)),
                (
                    "id_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="life_habits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MedicalHistory",
            fields=[
                (
                    "id_medical_history",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("current_medications", models.TextField(blank=True, null=True)),
                ("allergies", models.TextField(blank=True, null=True)),
                ("surgeries", models.TextField(blank=True, null=True)),
                ("family_history", models.TextField(blank=True, null=True)),
                ("blood_type", models.CharField(blank=True, max_length=3, null=True)),
                (
                    "health_plan",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "emergency_contacts",
                    models.ManyToManyField(
                        related_name="medical_history", to="api_rest.emergencycontact"
                    ),
                ),
                (
                    "id_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="medical_history",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Availability",
            fields=[
                (
                    "id_availability",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("date", models.DateField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                (
                    "id_doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="availabilities",
                        to="api_rest.doctor",
                    ),
                ),
            ],
            options={
                "unique_together": {("id_doctor", "date", "start_time", "end_time")},
            },
        ),
        migrations.CreateModel(
            name="Appointment",
            fields=[
                ("id_appointment", models.AutoField(primary_key=True, serialize=False)),
                ("date", models.DateField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "id_patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "id_doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="appointments",
                        to="api_rest.doctor",
                    ),
                ),
            ],
            options={
                "unique_together": {("id_doctor", "date", "start_time", "end_time")},
            },
        ),
    ]
