# Generated by Django 5.0.6 on 2024-06-14 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0004_doctor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id_availability', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('id_professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='api_rest.doctor')),
            ],
            options={
                'unique_together': {('id_professional', 'date', 'start_time', 'end_time')},
            },
        ),
    ]
