# Generated by Django 5.0.6 on 2024-06-19 19:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0005_availability'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id_appointment', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('id_professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='api_rest.doctor')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('id_professional', 'date', 'start_time', 'end_time')},
            },
        ),
    ]
